name: opendungeons-plus
version: 0.8.0+new-editorimproved-shaders
confinement: strict
summary: OpenDungeons
base: core20
description: Open source game inspired by Dungeon Keeper - Dark, damp and dangerous.

apps:
    opendungeons-plus:
        command: bin/desktop-launch $SNAP/usr/games/opendungeons-plus
        environment:
            CEGUI_MODULE_DIR: $SNAP/usr/lib/cegui-0.9999
        plugs: [opengl, x11, pulseaudio, network, network-bind]
        desktop: usr/share/applications/opendungeons-plus.desktop
        
architectures:
  - build-on: amd64
  - build-on: i386        
  
parts:
    desktop-glib-only:
        source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
        source-subdir: glib-only
        plugin: make
    ogre:
        plugin: cmake
        cmake-parameters:
            - -DCMAKE_BUILD_TYPE=Release
            - -DOGRE_CONFIG_THREAD_PROVIDER=std
            - -DOGRE_CONFIG_THREADS=3
            - -DOGRE_STATIC=FALSE
            - -DOGRE_BUILD_DEPENDENCIES=FALSE
            - -DOGRE_BUILD_RENDERSYSTEM_GL=TRUE
            - -DOGRE_BUILD_RENDERSYSTEM_GL3PLUS=TRUE
            - -DOGRE_RESOURCEMANAGER_STRICT=0
            # stuff we dont need
            - -DOGRE_BUILD_RENDERSYSTEM_GLES2=FALSE
            - -DOGRE_BUILD_TOOLS=FALSE
            - -DOGRE_BUILD_SAMPLES=FALSE
            - -DOGRE_BUILD_PLUGIN_FREEIMAGE=FALSE
            - -DOGRE_BUILD_PLUGIN_EXRCODEC=FALSE
            - -DOGRE_BUILD_PLUGIN_BSP=FALSE
            - -DOGRE_BUILD_PLUGIN_PCZ=FALSE
            - -DOGRE_BUILD_PLUGIN_DOT_SCENE=FALSE
            - -DOGRE_BUILD_COMPONENT_JAVA=FALSE
            - -DOGRE_BUILD_COMPONENT_VOLUME=FALSE
            - -DOGRE_BUILD_COMPONENT_PAGING=FALSE
            - -DOGRE_BUILD_COMPONENT_TERRAIN=FALSE
            - -DOGRE_BUILD_COMPONENT_PROPERTY=FALSE
            - -DOGRE_BUILD_COMPONENT_MESHLODGENERATOR=FALSE
            - -DOGRE_BUILD_COMPONENT_HLMS=FALSE
            - -DCMAKE_INSTALL_PREFIX=/usr/
            - -DOGRE_ENABLE_PRECOMPILED_HEADERS=OFF
        source: https://github.com/OGRECave/ogre.git
        source-tag: v1.12.13
        source-depth: 1
        build-packages:
            - libxaw7-dev
            - libzzip-dev
            - libxrandr-dev
            - libfreetype6-dev
            - libxt-dev
            - libgl1-mesa-dev
            - libegl1-mesa-dev
            - libglu1-mesa-dev
            - g++
        stage-packages:
            - libegl1-mesa
            - libfreetype6
            - libzzip-0-13
            - libxaw7
            - libxt6
            - libgl1
            - libglvnd0
            - libglx0
            - libxrandr2
            - libxrender1
    cegui:
        plugin: cmake
        cmake-parameters:
            - -DCMAKE_BUILD_TYPE=Release
            - -DCMAKE_INSTALL_PREFIX=/usr/
            - -DCEGUI_BUILD_RENDERER_OPENGL=FALSE
            - -DCEGUI_BUILD_RENDERER_OPENGLES=FALSE
            - -DCEGUI_BUILD_RENDERER_OPENGL3=FALSE
            - -DCEGUI_BUILD_IMAGECODEC_FREEIMAGE=FALSE # we use ogre
            - -DCEGUI_OPTION_DEFAULT_IMAGECODEC=OgreRenderer-0
            - -DCEGUI_SAMPLES_ENABLED=FALSE
        source: https://github.com/tomluchowski/cegui.git
        source-depth: 1
        source-tag: v0
        build-packages:
            - librapidxml-dev
        build-environment:
            - CMAKE_PREFIX_PATH: $CMAKE_PREFIX_PATH:$SNAPCRAFT_STAGE/usr/            
        override-pull: |
            snapcraftctl pull
            sed -i -e 's|target_compile_features|\#target_compile_features|g' cegui/src/RendererModules/Ogre/CMakeLists.txt
        after: [ogre]
    libois:
        plugin: cmake
        source: https://github.com/wgois/OIS.git
        source-depth: 1
        source-tag: v1.5
        override-pull: |
            snapcraftctl pull
        build-packages:
            - libc6
            - libstdc++6
            - libx11-6
        stage-packages:
            - libc6
            - libstdc++6
            - libx11-6
        after: [cegui]        
    opendungeons-plus:
        plugin: cmake
        source: https://github.com/tomluchowski/OpenDungeonsPlus.git
        source-tag: shaders-improvement
        source-depth: 1
        build-environment:
            - CMAKE_PREFIX_PATH: $CMAKE_PREFIX_PATH:$SNAPCRAFT_STAGE/usr
        override-pull: |
            snapcraftctl pull
            sed -i -e 's|if(CMAKE_INSTALL_PREFIX|if(""|g' CMakeLists.txt
        cmake-parameters:
            - -DCMAKE_BUILD_TYPE=Release
            - -DCMAKE_INSTALL_PREFIX=/usr/
            - -DOD_TREAT_WARNINGS_AS_ERRORS=OFF
            
        override-build: |
            snapcraftctl build
            sed -i -e 's|/.*/stage||g' $SNAPCRAFT_PART_INSTALL/etc/opendungeons-plus/plugins.cfg # drop stage prefix
            sed -i -e 's|/.*/stage||g' $SNAPCRAFT_PART_INSTALL/usr/share/games/opendungeons-plus/resources.cfg # drop stage prefix
        build-packages:
            - pkg-config
            - libsfml-dev
            - libboost-thread-dev
            - libboost-locale-dev
            - libboost-filesystem-dev
            - libboost-program-options-dev
            - libpython3.9-dev
            - pybind11-dev
            - python3-distutils
            - python3-distutils-extra
        stage-packages:
            - libsfml-window2.5
            - libsfml-audio2.5
            - libsfml-system2.5
            - libsfml-network2.5
            - libboost-thread1.71.0
            - libboost-program-options1.71.0
            - libboost-filesystem1.71.0
            - libboost-system1.71.0
            - libboost-locale1.71.0
            - libboost-chrono1.71.0
            - libpulse0
            - python3

        after: [ogre, cegui, desktop-glib-only,libois]
